// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxi9Y-VkIaAiUr6WmXnxt5TR4Pqo7scU',
    appId: '1:454416912877:web:cdbaa1df6f9f447d7017e4',
    messagingSenderId: '454416912877',
    projectId: 'have-you-ever-been-like-that',
    authDomain: 'have-you-ever-been-like-that.firebaseapp.com',
    storageBucket: 'have-you-ever-been-like-that.firebasestorage.app',
    measurementId: 'G-2TWFMZ4HKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkP6tCsE0ra9DOsWjyFNMfs9Kvc-qbGLc',
    appId: '1:454416912877:android:840ffeb9b208fce97017e4',
    messagingSenderId: '454416912877',
    projectId: 'have-you-ever-been-like-that',
    storageBucket: 'have-you-ever-been-like-that.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUn9o0XyvgN-2JzprOx38FuzZmxM2sLEU',
    appId: '1:454416912877:ios:3a92e1584d62a0527017e4',
    messagingSenderId: '454416912877',
    projectId: 'have-you-ever-been-like-that',
    storageBucket: 'have-you-ever-been-like-that.firebasestorage.app',
    iosBundleId: 'com.inu.haveyoueverbeenlikethat.haveYouEverBeenLikeThat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUn9o0XyvgN-2JzprOx38FuzZmxM2sLEU',
    appId: '1:454416912877:ios:3a92e1584d62a0527017e4',
    messagingSenderId: '454416912877',
    projectId: 'have-you-ever-been-like-that',
    storageBucket: 'have-you-ever-been-like-that.firebasestorage.app',
    iosBundleId: 'com.inu.haveyoueverbeenlikethat.haveYouEverBeenLikeThat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByxi9Y-VkIaAiUr6WmXnxt5TR4Pqo7scU',
    appId: '1:454416912877:web:95ece20386a390297017e4',
    messagingSenderId: '454416912877',
    projectId: 'have-you-ever-been-like-that',
    authDomain: 'have-you-ever-been-like-that.firebaseapp.com',
    storageBucket: 'have-you-ever-been-like-that.firebasestorage.app',
    measurementId: 'G-CY0QCTXCGF',
  );
}
